### ISSUE TITLE
OSError: [Errno 30] Read-only file system: '/data'

### ISSUE THREAD

**Issue by ArronAI007** [gomate-community/GoMate#62]
把app.py文件20-32行替换成对应的本地模型，在执行python app.py的时候，
报错如下：
项目根目录为: /Users/hezhidong/Desktop/RAG/GoMate
Traceback (most recent call last):
  File "/Users/hezhidong/Desktop/RAG/GoMate/app.py", line 16, in <module>
    from gomate.applications.rag import RagApplication, ApplicationConfig
  File "/Users/hezhidong/Desktop/RAG/GoMate/gomate/applications/__init__.py", line 1, in <module>
    from .rewriter import RewriterApp
  File "/Users/hezhidong/Desktop/RAG/GoMate/gomate/applications/rewriter.py", line 1, in <module>
    from gomate.modules.rewriter.hyde_rewriter import HydeRewriter
  File "/Users/hezhidong/Desktop/RAG/GoMate/gomate/modules/rewriter/hyde_rewriter.py", line 18, in <module>
    from gomate.modules.document.common_parser import CommonParser
  File "/Users/hezhidong/Desktop/RAG/GoMate/gomate/modules/document/common_parser.py", line 5, in <module>
    from gomate.modules.document.chunk import TextChunker
  File "/Users/hezhidong/Desktop/RAG/GoMate/gomate/modules/document/chunk.py", line 3, in <module>
    from gomate.modules.document import rag_tokenizer
  File "/Users/hezhidong/Desktop/RAG/GoMate/gomate/modules/document/rag_tokenizer.py", line 24, in <module>
    from gomate.modules.document.utils import get_project_base_directory
  File "/Users/hezhidong/Desktop/RAG/GoMate/gomate/modules/document/utils.py", line 151, in <module>
    encoder = tiktoken.get_encoding("cl100k_base")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/gomate/lib/python3.11/site-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/gomate/lib/python3.11/site-packages/tiktoken_ext/openai_public.py", line 72, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
                      ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/gomate/lib/python3.11/site-packages/tiktoken/load.py", line 147, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file, expected_hash)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/gomate/lib/python3.11/site-packages/tiktoken/load.py", line 72, in read_file_cached
    os.makedirs(cache_dir, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 3 more times]
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '/data'

请问是什么原因呢？看起来是写入/data的时候报错了

**Comment by yanqiangmiffy** [comment]
RAG技术交流群
GoMate地址：https://github.com/gomate-community/GoMate

nltk和huiqie下载地址：链接：https://pan.baidu.com/s/1C8zJHgdL6mbzWWmqqEF2Og?pwd=b3q1 
提取码：b3q1
